permissions:
  contents: write
  pull-requests: write 
  issues: read

name: mlops-ci-tf-regression
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          pip install -r requirements.txt
          python model.py  
          
          # Create CML report
          
          echo "## Model Metrics ##" > report.md
          cat metrics.txt >> report.md
          echo "\n## Model Performance ##" >> report.md
          echo "![](./model_results.png)" >> report.md
          
          cml comment create report.md
          
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
